### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by erdvillegasxpt** [some-natalie/ghas-to-csv#24]
We have getting this error while are runing the job,

```py
Traceback (most recent call last):
Found 2 code scanning alerts in XPERTAL
  File "/app/main.py", line 75, in <module>
    code_scanning.write_org_cs_list(cs_list)
  File "/app/src/code_scanning.py", line 191, in write_org_cs_list
    if cs["state"] == "open":
TypeError: string indices must be integers
```

Is there any wrong option

**Comment by some-natalie** [comment]
Hey, more than likely, the PAT you specified has the wrong scopes for what you're asking it to do.

https://github.com/some-natalie/ghas-to-csv#how should help on the yaml input and the appropriate PAT scopes

https://github.com/some-natalie/ghas-to-csv/issues/9 has more info around tracking the work to fix it.
