### ISSUE TITLE
Org reports - updated to V2

### ISSUE THREAD

**Issue by yrsurya** [some-natalie/ghas-to-csv#25]
Thanks so much for getting this again

It worked previously but now while trying to upgrade from main to v2 seeing following errors

Traceback (most recent call last):
Found 3 code scanning alerts in {org_name}
  File "/app/main.py", line 80(https://github.com/{org_name}/secret-scanning-reports/actions/runs/3229973268/jobs/5287886231#step:6:9)0, in <module>
    secret_scanning.write_org_secrets_list(secrets_list)
  File "/app/src/secret_scanning.py", line 212, in write_org_secrets_list
    alert["resolved_by"]["login"],
TypeError: 'NoneType' object is not subscriptable
Found 3 code scanning alerts in {org_name}
Found 1549(https://github.com/{org_name}/secret-scanning-reports/actions/runs/3229973268/jobs/5287886231#step:6:10) secret scanning alerts in {org_name}

Here is my workflow

      # Runs a report
      - name: CSV export
        uses: some-natalie/ghas-to-csv@v2
        env:
          GITHUB_PAT: ${{ secrets.PAT }}  # if you need to set a custom PAT
          GITHUB_REPORT_SCOPE: "organization"
          SCOPE_NAME: "{org_name}"
      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: ghas-data
          path: ${{ github.workspace }}/*.csv
          if-no-files-found: error

Please suggest

https://github.com/some-natalie/ghas-to-csv/issues/25#tasklist-block-c1ce74cc-5d4a-4120-b7d5-2bec5c20b2da

**Comment by yrsurya** [comment]
I provided all required scopes and it even reported correct numbers  Found 1549, Found 3 code scanning alerts 

but failing with this error 

Found 3 code scanning alerts in
Traceback (most recent call last):
  File "/app/main.py", line 5[9](https://github.com//secret-scanning-reports/actions/runs/3321687250/jobs/5489674056#step:6:10), in <module>
    secret_scanning.write_org_secrets_list(secrets_list)
Found 1544 secret scanning alerts in 
  File "/app/src/secret_scanning.py", line 2[12](https://github.com//secret-scanning-reports/actions/runs/3321687250/jobs/5489674056#step:6:13), in write_org_secrets_list
    alert["resolved_by"]["login"],
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
